ARG BASE_IMAGE
FROM $BASE_IMAGE

RUN apt-get -y update --fix-missing

# aws cli
RUN curl -L https://awscli.amazonaws.com/awscli-exe-linux-$(uname -m).zip -o "awscliv2.zip"
RUN unzip awscliv2.zip && ./aws/install && rm -rf awscliv2.zip aws
